name: TEST Build
on:
  workflow_dispatch:
env:
  REPO_TOKEN:  ${{ secret.PRIVATE_REPO_TOKEN }}
  REPO: ${{ secret.REPO }}

jobs:
  Windows-build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v2
        with:
          token: ${{ env.PRIVATE_REPO_TOKEN }}
          ref: main
          repository: ${{ env.REPO }}
      - name: 打印目录文件
        run: |
          ls
